### ISSUE TITLE
Retain title when toggling between "Maintenance" and "Task"

### ISSUE THREAD

**Issue by prometheas** [CommunityAlly/CommunityAllyWebApp#2]
When interacting with `#!/Info/Maintenance`'s _Add New Entry_ dialog, toggling between "Maintenance Entry" and "To-Do" radio buttons should retain text entered into the _Name_ field of either form.

**Comment by TaylorClark** [comment]
Thanks again for taking the time to suggest this, John.

**Comment by prometheas** [comment]
🎉
