### ISSUE TITLE
Uploading 74.1 MB mp4 file failed with mysterious message

### ISSUE THREAD

**Issue by prometheas** [CommunityAlly/CommunityAllyWebApp#7]
Uploading 74.1 MB mp4 file failed with following message:

![image](https://user-images.githubusercontent.com/185966/62838993-ae0d7080-bc51-11e9-8f43-f17dfd63d157.png)

**Comment by CommunityAlly** [comment]
Thanks, John. It should have shown a more descriptive error explaining 50MB is the max size. We'll get this fixed up.
